apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: shortkenny
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/shortkenny:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: DB_DSN
          value: "sqlite:/var/www/html/data/data.sqlite"
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "1"
            memory: 512Mi

